# Generated by Django 4.2.14 on 2024-08-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=255)),
                ('property_type', models.CharField(default='', max_length=100)),
                ('features', models.TextField(default='')),
                ('video_url', models.URLField(default='')),
                ('image_url', models.URLField(default='')),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
    ]
