# Generated by Django 4.2.15 on 2024-08-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_image_url_remove_property_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
    ]
