# Generated by Django 4.2.15 on 2024-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('Oristano', 'Oristano'), ('Torregrande', 'Torregrande'), ('Nolosodove', 'Nolosodove')], default='Oristano', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa')], default='House', max_length=50),
        ),
    ]
