# Generated by Django 4.2.15 on 2024-08-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_rename_image_property_main_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
